<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StudentUsers', 'doctrine');

/**
 * BaseStudentUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $snum
 * @property string $p_word
 * @property Doctrine_Collection $ProjectAllocations
 * @property Doctrine_Collection $ProjectAllocations_3
 * @property Doctrine_Collection $ProjectAllocations_4
 * @property Doctrine_Collection $ProjectAllocations_5
 * @property Doctrine_Collection $ProjectAllocations_6
 * @property Doctrine_Collection $ProjectAllocations_7
 * @property Doctrine_Collection $StudentPrefs
 * 
 * @method integer             getSnum()                 Returns the current record's "snum" value
 * @method string              getPWord()                Returns the current record's "p_word" value
 * @method Doctrine_Collection getProjectAllocations()   Returns the current record's "ProjectAllocations" collection
 * @method Doctrine_Collection getProjectAllocations3()  Returns the current record's "ProjectAllocations_3" collection
 * @method Doctrine_Collection getProjectAllocations4()  Returns the current record's "ProjectAllocations_4" collection
 * @method Doctrine_Collection getProjectAllocations5()  Returns the current record's "ProjectAllocations_5" collection
 * @method Doctrine_Collection getProjectAllocations6()  Returns the current record's "ProjectAllocations_6" collection
 * @method Doctrine_Collection getProjectAllocations7()  Returns the current record's "ProjectAllocations_7" collection
 * @method Doctrine_Collection getStudentPrefs()         Returns the current record's "StudentPrefs" collection
 * @method StudentUsers        setSnum()                 Sets the current record's "snum" value
 * @method StudentUsers        setPWord()                Sets the current record's "p_word" value
 * @method StudentUsers        setProjectAllocations()   Sets the current record's "ProjectAllocations" collection
 * @method StudentUsers        setProjectAllocations3()  Sets the current record's "ProjectAllocations_3" collection
 * @method StudentUsers        setProjectAllocations4()  Sets the current record's "ProjectAllocations_4" collection
 * @method StudentUsers        setProjectAllocations5()  Sets the current record's "ProjectAllocations_5" collection
 * @method StudentUsers        setProjectAllocations6()  Sets the current record's "ProjectAllocations_6" collection
 * @method StudentUsers        setProjectAllocations7()  Sets the current record's "ProjectAllocations_7" collection
 * @method StudentUsers        setStudentPrefs()         Sets the current record's "StudentPrefs" collection
 * 
 * @package    PANS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_users');
        $this->hasColumn('snum', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('p_word', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProjectAllocations', array(
             'local' => 'snum',
             'foreign' => 'snum6'));

        $this->hasMany('ProjectAllocations as ProjectAllocations_3', array(
             'local' => 'snum',
             'foreign' => 'snum1'));

        $this->hasMany('ProjectAllocations as ProjectAllocations_4', array(
             'local' => 'snum',
             'foreign' => 'snum2'));

        $this->hasMany('ProjectAllocations as ProjectAllocations_5', array(
             'local' => 'snum',
             'foreign' => 'snum3'));

        $this->hasMany('ProjectAllocations as ProjectAllocations_6', array(
             'local' => 'snum',
             'foreign' => 'snum4'));

        $this->hasMany('ProjectAllocations as ProjectAllocations_7', array(
             'local' => 'snum',
             'foreign' => 'snum5'));

        $this->hasMany('StudentPrefs', array(
             'local' => 'snum',
             'foreign' => 'snum'));
    }
}