<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SkillSets', 'doctrine');

/**
 * BaseSkillSets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $area
 * @property integer $is_visible
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getArea()       Returns the current record's "area" value
 * @method integer   getIsVisible()  Returns the current record's "is_visible" value
 * @method SkillSets setId()         Sets the current record's "id" value
 * @method SkillSets setArea()       Sets the current record's "area" value
 * @method SkillSets setIsVisible()  Sets the current record's "is_visible" value
 * 
 * @package    PANS
 * @subpackage model
 * @author     Daniel Brose
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSkillSets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skill_sets');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('area', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('is_visible', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}