<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdminUsers', 'doctrine');

/**
 * BaseAdminUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $p_word
 * 
 * @method string     getUsername() Returns the current record's "username" value
 * @method string     getPWord()    Returns the current record's "p_word" value
 * @method AdminUsers setUsername() Sets the current record's "username" value
 * @method AdminUsers setPWord()    Sets the current record's "p_word" value
 * 
 * @package    PANS
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdminUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('admin_users');
        $this->hasColumn('username', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('p_word', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}