<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('StudentUsers', 'doctrine');

/**
 * BaseStudentUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $snum
 * @property string $p_word
 * @property string $first_name
 * @property string $last_name
 * @property Doctrine_Collection $ProjectAllocations
 * 
 * @method integer             getSnum()               Returns the current record's "snum" value
 * @method string              getPWord()              Returns the current record's "p_word" value
 * @method string              getFirstName()          Returns the current record's "first_name" value
 * @method string              getLastName()           Returns the current record's "last_name" value
 * @method Doctrine_Collection getProjectAllocations() Returns the current record's "ProjectAllocations" collection
 * @method StudentUsers        setSnum()               Sets the current record's "snum" value
 * @method StudentUsers        setPWord()              Sets the current record's "p_word" value
 * @method StudentUsers        setFirstName()          Sets the current record's "first_name" value
 * @method StudentUsers        setLastName()           Sets the current record's "last_name" value
 * @method StudentUsers        setProjectAllocations() Sets the current record's "ProjectAllocations" collection
 * 
 * @package    PANS
 * @subpackage model
 * @author     Daniel Brose
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_users');
        $this->hasColumn('snum', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('p_word', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('first_name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('last_name', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProjectAllocations', array(
             'local' => 'snum',
             'foreign' => 'snum1'));
    }
}