
# Export routing rule  - NOT IN USE
#export_excel:
#    url:    /export.csv
#    param: {module: project, action: export}
    
    
project_allocation:
  class: sfDoctrineRouteCollection
  options:
    model:                ProjectAllocation
    module:               group
    prefix_path:          /group
    column:               project_id
    with_wildcard_routes: true

skill_set:
  class: sfDoctrineRouteCollection
  options:
    model:                SkillSet
    module:               skill
    prefix_path:          /skill
    column:               id
    with_wildcard_routes: true

major:
  class: sfDoctrineRouteCollection
  options:
    model:                Major
    module:               major
    prefix_path:          /major
    column:               id
    with_wildcard_routes: true

degree:
  class: sfDoctrineRouteCollection
  options:
    model:                Degree
    module:               degree
    prefix_path:          /degree
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

student_user:
  class: sfDoctrineRouteCollection
  options:
    model:                StudentUser
    module:               student
    prefix_path:          /student
    column:               snum
# sfAdminGenerator hack
#    with_wildcard_routes: true

project:
  class: sfDoctrineRouteCollection
  options:
    model:                Project
    module:               project
    prefix_path:          /project
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: student, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
  
default:
  url:   /:module/:action/*
