student_user:
  class: sfDoctrineRouteCollection
  options:
    model:                StudentUser
    module:               student
    prefix_path:          /student
    column:               snum
    with_wildcard_routes: true

project:
  class: sfDoctrineRouteCollection
  options:
    model:                Project
    module:               project
    prefix_path:          /project
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: student, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:project
  param: { action: index }

default:
  url:   /:module/:action/*
