<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/02 07:14:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pans',
  'username' => 'root',
  'password' => 'timemachine',
  'name' => 'doctrine',
)),);
