<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/18 09:11:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pinpoint_db',
  'username' => 'root',
  'password' => '3001ictrules',
  'name' => 'doctrine',
)),);
