<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/05/26 03:50:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=pans',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
