<?php

/**
 * AdminUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdminUsers');
    }
}