<?php

/**
 * DegreeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DegreeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DegreeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Degree');
    }
}