<?php

/**
 * EmailDomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailDomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailDomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EmailDomain');
    }
}