<?php

/**
 * MajorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MajorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MajorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Major');
    }
}