<?php

/**
 * NominationRoundTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NominationRoundTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NominationRoundTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NominationRound');
    }
}