<?php

/**
 * ProjectAllocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectAllocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectAllocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectAllocation');
    }
}