<?php

/**
 * ProjectAllocationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectAllocationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectAllocationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectAllocations');
    }
}