<?php

/**
 * SkillSetsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkillSetsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkillSetsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SkillSets');
    }
}