<?php

/**
 * SkillSetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkillSetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkillSetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SkillSet');
    }
}