<?php

/**
 * StudentUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentUsers');
    }
}