<?php

/**
 * StudentUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentUser');
    }

    /*
     * Dummy function for JQuery Autucompletion to work
     * Because everyone assumes the field to be ID. Bleh.
     */
    public static function findOneById($id)
    {
        return Doctrine_Core::getTable('StudentUser')->find(array($id));
    }
}
