<?php

/**
 * StudentPrefsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentPrefsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentPrefsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentPrefs');
    }
}