<?php

/**
 * StudentUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentUser');
    }
}