# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        Project Allocation and Nomination System
    #description:  Online form for 3001ICT students to select projects
    #keywords:     student projects allocation nomination
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, pans.css]

# A non-limited licence (MIT license) js script (getElementsByClass...) was used to ensure cross, and backwards, compatability with IE and other browsers.
  javascripts:    [jquery-1.6.3.min.js, studentForm_Instructions.js, getElementsByClassName-1.0.1.js]

  has_layout:     true
  layout:         layout
