generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Major
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          major
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        title:   Majors
        display: [id, =major]
        batch_actions: {}
        max_per_page: 99999
      # Stops Symfony from displaying the filter in the admin view
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
