generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Degree
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          degree
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title:   Degrees
        display: [id, =degree]
        batch_actions: {}
        max_per_page: 99999
      # Stops Symfony from displaying the filter in the admin view
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
