generator:
  class: sfDoctrineGenerator
  param:
    model_class:           project
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~            
      list:
        title:   Projects
        display: [=title, organisation]
        batch_actions: {}
      # Stops Symfony from displaying the filter in the admin view
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
