generator:
  class: sfDoctrineGenerator
  param:
    model_class:           project
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      fields:  ~            
      actions: ~
      list:
        title:   Project List
        display: [title, organisation]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
