Projects:
  proj_1:
    title: Bring Your Daughter To Work Day
    organisation: Aperture Science
    description: |
      Bring a potato.
      Bring your daughter.
      No cats.
      Have fun.
    has_additional_info: false
    major_ids: 1 2 3
    skill_set_ids: 1 2 3
    nomination_round:
    proj_num: 1
  proj_2:
    title: Build a Portal Gun
    organisation: Portal Fans
    description: |
      Pew pew pew!
      If you go through the blue portal, you come out from the orange one.
    has_additional_info: true
    major_ids: 1 2
    skill_set_ids: 4 5
    nomination_round:
    proj_num: 2