Major:
  connection: doctrine
  tableName: majors
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    major:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Degree:
  connection: doctrine
  tableName: degrees
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      unsigned: false
      primary: true
      autoincrement: true
    degree:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
ProjectAllocation:
  connection: doctrine
  tableName: project_allocations
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      unsigned: false
      primary: true
      autoincrement: true
    project_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      autoincrement: false
    snum:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Project:
      onDelete: CASCADE
      local: project_id
      type: one
      foreignType: many
      foreign: id
    StudentUser:
      onDelete: CASCADE
      local: snum
      type: one
      foreignType: many
      foreign: snum
Project:
  connection: doctrine
  tableName: projects
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    organisation:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    has_additional_info:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    has_gpa_cutoff:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    major_ids:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    skill_set_ids:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
SkillSet:
  connection: doctrine
  tableName: skill_sets
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    skill:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
StudentUser:
  connection: doctrine
  tableName: student_users
  actAs:
    Timestampable:
      create:
        disabled: true
      updated:
        disabled: false
  columns:
    snum:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    first_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    pass_fail_pm:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    major_ids:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    degree_ids:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    gpa:
      type: float(18)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    proj_pref1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    skill_set_ids:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just1:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just2:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just3:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just4:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just5:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    form_completed:
      type: boolean
      notnull: true
      default: false
      autoincrement: false
      fixed: false
      unsigned: false
      primary: false
  relations:
    Project:
      onDelete: CASCADE
      local: proj_pref1
      type: one
      foreignType: many
      foreign: id
    StudentUser:
      onDelete: CASCADE
      local: y_stu_pref1
      type: one
      foreignType: many
      foreign: snum
    Degree:
      onDelete: CASCADE
      local: degree_ids
      type: many
      foreignType: many
      foreign: id
    Major:
      onDelete: CASCADE
      local: major_ids
      type: many
      foreignType: many
      foreign: id
    SkillSet:
      onDelete: CASCADE
      local: skill_set_ids
      type: many
      foreignType: many
      foreign: id
NominationRound:
  connection: doctrine
  tableName: nomination_round
  columns:
    deadline:
      type: date
      primary: true