AdminUsers:
  connection: doctrine
  tableName: admin_users
  columns:
    username:
      type: string(64)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    p_word:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false

Majors:
  connection: doctrine
  tableName: majors
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    major:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    is_visible:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false


ProjectAllocations:
  connection: doctrine
  tableName: project_allocations
  columns:
    project_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    snum1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    snum2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    snum3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    snum4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    snum5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    snum6:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    StudentUsers:
      local: snum1
      foreign: snum
      type: one
    StudentUsers_2:
      class: StudentUsers
      local: snum2
      foreign: snum
      type: one
    StudentUsers_3:
      class: StudentUsers
      local: snum3
      foreign: snum
      type: one
    StudentUsers_4:
      class: StudentUsers
      local: snum4
      foreign: snum
      type: one
    StudentUsers_5:
      class: StudentUsers
      local: snum5
      foreign: snum
      type: one
    StudentUsers_6:
      class: StudentUsers
      local: snum6
      foreign: snum
      type: one
  
  
  
Projects:
  connection: doctrine
  tableName: projects
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    organisation:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    description:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    has_additional_info:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    major_ids:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    skill_set_ids:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nomination_round:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    proj_num:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false


  
SkillSets:
  connection: doctrine
  tableName: skill_sets
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    area:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    is_visible:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  
  
  
StudentPrefs:
  connection: doctrine
  tableName: student_prefs
  columns:
    snum:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nomination_round:
      type: string(64)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    pass_fail_pm:                        #_C_
      type: boolean
      fixed: false
      notnull: true
    major_ids:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    gpa:                        #_C_
      type: float(18)
      fixed: false
      default: "5.0" 
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref_1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref_2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref_3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref_4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_pref_5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    skill_set_ids:
      type: string(32)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref_1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref_2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref_3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref_4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    y_stu_pref_5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref_1:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref_2:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref_3:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref_4:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    n_stu_pref_5:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just_1:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just_2:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just_3:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just_4:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    proj_just_5:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:  #_C_                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! CHANGED !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
    Projects: { onDelete: CASCADE, local: proj_pref_1, foreign: id, foreignAlias: Project1 }  
    Projects: { onDelete: CASCADE, local: proj_pref_2, foreign: id, foreignAlias: Project2 }     
    
  
  
StudentUsers:
  connection: doctrine
  tableName: student_users
  columns:
    snum:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    p_word:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    first_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    last_name:
      type: string(64)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    ProjectAllocations:
      local: snum
      foreign: snum1
      type: many
    ProjectAllocations_2:
      class: ProjectAllocations
      local: snum
      foreign: snum2
      type: many
    ProjectAllocations_3:
      class: ProjectAllocations
      local: snum
      foreign: snum3
      type: many
    ProjectAllocations_4:
      class: ProjectAllocations
      local: snum
      foreign: snum4
      type: many
    ProjectAllocations_5:
      class: ProjectAllocations
      local: snum
      foreign: snum5
      type: many
    ProjectAllocations_6:
      class: ProjectAllocations
      local: snum
      foreign: snum6
      type: many
