generator:
  class: sfDoctrineGenerator
  param:
    model_class:           StudentUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:   Student List
        display: [snum, first_name, last_name, form_completed]
        batch_actions: {}
        actions: 
          importStudentsFromExcel:
            label: Import Students From File
        max_per_page: 99999
      # Stops Symfony from displaying the filter in the admin view
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
